
var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.ue||(h.ue=0);h.ue++;
(function(a){function b(n,q,p){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(u){var v=q;u.total&&(v=u.total);if(u.loaded){t.Od?h.de[n].loaded=u.loaded:(t.Od=!0,h.de||(h.de={}),h.de[n]={loaded:u.loaded,total:v});var z=v=u=0,B;for(B in h.de){var F=h.de[B];u+=F.total;v+=F.loaded;z++}u=Math.ceil(u*h.ue/z);h.setStatus&&h.setStatus("Downloading data... ("+v+"/"+u+")")}else!h.de&&h.setStatus&&h.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,v,z){this.start=u;this.he=v;this.audio=z}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.Ee=u;u=a.files;for(var v=0;v<
u.length;++v)n.prototype.Od[u[v].filename].onload();h.removeRunDependency("datafile_dest/index.data")}n.prototype={Od:{},open:function(u,v){this.name=v;this.Od[v]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.De(this.Ee.subarray(this.start,this.he))},De:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.Od[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio)).open("GET",
p[t].filename);h.addRunDependency("datafile_dest/index.data");h.Ye||(h.Ye={});h.Ye["dest/index.data"]={Hf:!1};m?(q(m),m=null):g=q}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{filename:"/base_scene.obj",
start:0,end:84652,audio:0}],remote_package_size:84652,package_uuid:"eb0f92eb-6b22-4c3c-a068-db7345d6cfd4"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;var l="",ka,la,na,oa,pa,qa;
if(ia)l=ha?require("path").dirname(l)+"/":__dirname+"/",ka=function(a,b){pa||(pa=require("fs"));qa||(qa=require("path"));a=qa.normalize(a);return pa.readFileSync(a,b?null:"utf8")},na=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ra))throw a;}),process.on("unhandledRejection",
r),ea=function(a){process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?l=self.location.href:"undefined"!==typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},oa=function(a){document.title=a};var sa=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ua(a){va||(va={});va[a]||(va[a]=1,k(a))}var va,wa;h.wasmBinary&&(wa=h.wasmBinary);var noExitRuntime;h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);"object"!==typeof WebAssembly&&r("no native wasm support detected");
function xa(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":w[a>>0]=b;break;case "i8":w[a>>0]=b;break;case "i16":ya[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":za=[b>>>0,(y=b,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];x[a>>2]=za[0];x[a+4>>2]=za[1];break;case "float":A[a>>2]=b;break;case "double":C[a>>3]=b;break;default:r("invalid type for setValue: "+c)}}var Aa,Ba=!1;
function assert(a,b){a||r("Assertion failed: "+b)}function Ca(a){var b=h["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Da(a,b,c,d){var e={string:function(q){var p=0;if(null!==q&&void 0!==q&&0!==q){var t=(q.length<<2)+1;p=Ea(t);D(q,p,t)}return p},array:function(q){var p=Ea(q.length);w.set(q,p);return p}},f=Ca(a),g=[];a=0;if(d)for(var m=0;m<d.length;m++){var n=e[c[m]];n?(0===a&&(a=Fa()),g[m]=n(d[m])):g[m]=d[m]}c=f.apply(null,g);c=function(q){return"string"===b?E(q):"boolean"===b?!!q:q}(c);0!==a&&Ga(a);return c}var Ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ia(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function E(a,b){return a?Ia(G,a,b):""}
function Ja(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function D(a,b,c){return Ja(a,G,b,c)}
function Ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function La(a){var b=Ka(a)+1,c=H(b);c&&Ja(a,w,c,b);return c}function Ma(a){var b=Ka(a)+1,c=Ea(b);Ja(a,w,c,b);return c}var Na,w,G,ya,Oa,x,Pa,A,C,Qa=h.INITIAL_MEMORY||16777216;h.wasmMemory?Aa=h.wasmMemory:Aa=new WebAssembly.Memory({initial:Qa/65536,maximum:Qa/65536});Aa&&(Na=Aa.buffer);Qa=Na.byteLength;var Ra=Na;
Na=Ra;h.HEAP8=w=new Int8Array(Ra);h.HEAP16=ya=new Int16Array(Ra);h.HEAP32=x=new Int32Array(Ra);h.HEAPU8=G=new Uint8Array(Ra);h.HEAPU16=Oa=new Uint16Array(Ra);h.HEAPU32=Pa=new Uint32Array(Ra);h.HEAPF32=A=new Float32Array(Ra);h.HEAPF64=C=new Float64Array(Ra);var I,Sa=[],Ta=[],Ua=[],Va=[],Wa=[];function Xa(){var a=h.preRun.shift();Sa.unshift(a)}var Ya=0,Za=null,$a=null;function ab(){Ya++;h.monitorRunDependencies&&h.monitorRunDependencies(Ya)}
function bb(){Ya--;h.monitorRunDependencies&&h.monitorRunDependencies(Ya);if(0==Ya&&(null!==Za&&(clearInterval(Za),Za=null),$a)){var a=$a;$a=null;a()}}h.preloadedImages={};h.preloadedAudios={};function r(a){if(h.onAbort)h.onAbort(a);k(a);Ba=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function cb(a){var b=db;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function eb(){return cb("data:application/octet-stream;base64,")}
var db="index.wasm";if(!eb()){var fb=db;db=h.locateFile?h.locateFile(fb,l):l+fb}function gb(){try{if(wa)return new Uint8Array(wa);if(na)return na(db);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}function hb(){return wa||!fa&&!ha||"function"!==typeof fetch||cb("file://")?Promise.resolve().then(gb):fetch(db,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+db+"'";return a.arrayBuffer()}).catch(function(){return gb()})}
var y,za,kb={1578:function(a){a=E(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=ib(a);var b=H(a.length);a.subarray||a.slice?G.set(a,b):G.set(new Uint8Array(a),b);return b},37564:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.cf!==h.canvas&&(d.Wd=h.createContext(h.canvas,!1,!0),d.cf=h.canvas);if(d.w!==a||d.kf!==b||d.mf!==d.Wd)d.image=d.Wd.createImageData(a,b),d.w=a,d.kf=b,d.mf=d.Wd;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&
a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=x[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ff!==a&&(d.df=new Int32Array(a.buffer),d.ef=new Uint8Array(a.buffer)),a=d.df,c=a.length,a.set(x.subarray(b,b+c)),a=d.ef,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Wd.putImageData(d.image,0,0);return 0},39043:function(a,
b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var q=x[e];b[m]=q&255;b[m+1]=q>>8&255;b[m+2]=q>>16&255;b[m+3]=q>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(x.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=H(c.length+
1);D(c,d,c.length+1);return d},40032:function(a){h.canvas&&(h.canvas.style.cursor=E(a));return 0},40125:function(){h.canvas&&(h.canvas.style.cursor="none")},41350:function(){return screen.width},41377:function(){return screen.height},41405:function(){return window.innerWidth},41437:function(){return window.innerHeight},41515:function(a){"undefined"!==typeof oa&&oa(E(a));return 0},41649:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},41815:function(){return"undefined"!==
typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},42041:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Nd||("undefined"!==typeof AudioContext?b.Nd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Nd=new webkitAudioContext),b.Nd&&jb(b.Nd));return void 0===b.Nd?-1:0},42594:function(){return h.SDL2.Nd.sampleRate},42664:function(a,b,c,d){function e(){}
function f(m){void 0!==g.capture.le&&(clearTimeout(g.capture.le),g.capture.le=void 0);g.capture.oe=g.Nd.createMediaStreamSource(m);g.capture.Qd=g.Nd.createScriptProcessor(b,a,1);g.capture.Qd.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.te=n.inputBuffer,n=[d],I.get(c).apply(null,n))};g.capture.oe.connect(g.capture.Qd);g.capture.Qd.connect(g.Nd.destination);g.capture.stream=m}var g=h.SDL2;g.capture.re=g.Nd.createBuffer(a,b,g.Nd.sampleRate);
g.capture.re.getChannelData(0).fill(0);g.capture.le=setTimeout(function(){g.capture.te=g.capture.re;var m=[d];I.get(c).apply(null,m)},b/g.Nd.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},44316:function(a,b,c,d){var e=h.SDL2;e.audio.Qd=e.Nd.createScriptProcessor(b,0,a);e.audio.Qd.onaudioprocess=
function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ke=f.outputBuffer,f=[d],I.get(c).apply(null,f))};e.audio.Qd.connect(e.Nd.destination)},44726:function(a,b){for(var c=h.SDL2,d=c.capture.te.numberOfChannels,e=0;e<d;++e){var f=c.capture.te.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)xa(a+4*g,f[g]);else for(g=0;g<b;++g)xa(a+4*(g*d+e),f[g])}},45331:function(a,b){for(var c=
h.SDL2,d=c.audio.Ke.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ke.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},45811:function(a){var b=h.SDL2;if(a){void 0!==b.capture.le&&clearTimeout(b.capture.le);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==
b.capture.Qd&&(b.capture.Qd.onaudioprocess=function(){},b.capture.Qd.disconnect(),b.capture.Qd=void 0);void 0!==b.capture.oe&&(b.capture.oe.disconnect(),b.capture.oe=void 0);void 0!==b.capture.re&&(b.capture.re=void 0);b.capture=void 0}else void 0!=b.audio.Qd&&(b.audio.Qd.disconnect(),b.audio.Qd=void 0),b.audio=void 0;void 0!==b.Nd&&void 0===b.audio&&void 0===b.capture&&(b.Nd.close(),b.Nd=void 0)}};function lb(a,b,c){a.addEventListener(b,c,{once:!0})}
function jb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&lb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function mb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Ne;"number"===typeof c?void 0===b.me?I.get(c)():I.get(c)(b.me):c(void 0===b.me?null:b.me)}}}function nb(){x[ob()>>2]=28}
function pb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function qb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=pb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function rb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function sb(a){if("/"===a)return"/";a=qb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function tb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){r("randomDevice")}}
function ub(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=pb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var vb=[];function wb(a,b){vb[a]={input:[],output:[],fe:b};xb(a,yb)}
var yb={open:function(a){var b=vb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.fe.flush(a.tty)},flush:function(a){a.tty.fe.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.fe.Oe)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.fe.Oe(a.tty)}catch(m){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.fe.ze)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.fe.ze(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},zb={Oe:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Od?Buffer.Od(256):new Buffer(256),d=0;try{d=pa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ib(b,!0)}return a.input.shift()},ze:function(a,b){null===b||10===b?(sa(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(sa(Ia(a.output,0)),a.output=[])}},Ab={ze:function(a,b){null===b||10===b?(k(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ia(a.output,0)),a.output=[])}},K={Yd:null,Zd:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Yd||(K.Yd={dir:{node:{ae:K.Kd.ae,Rd:K.Kd.Rd,lookup:K.Kd.lookup,pe:K.Kd.pe,rename:K.Kd.rename,unlink:K.Kd.unlink,rmdir:K.Kd.rmdir,readdir:K.Kd.readdir,symlink:K.Kd.symlink},stream:{ce:K.Ld.ce}},file:{node:{ae:K.Kd.ae,Rd:K.Kd.Rd},stream:{ce:K.Ld.ce,read:K.Ld.read,write:K.Ld.write,Fe:K.Ld.Fe,Te:K.Ld.Te,Ve:K.Ld.Ve}},link:{node:{ae:K.Kd.ae,Rd:K.Kd.Rd,readlink:K.Kd.readlink},stream:{}},Je:{node:{ae:K.Kd.ae,
Rd:K.Kd.Rd},stream:Bb}});c=Cb(a,b,c,d);16384===(c.mode&61440)?(c.Kd=K.Yd.dir.node,c.Ld=K.Yd.dir.stream,c.Jd={}):32768===(c.mode&61440)?(c.Kd=K.Yd.file.node,c.Ld=K.Yd.file.stream,c.Md=0,c.Jd=null):40960===(c.mode&61440)?(c.Kd=K.Yd.link.node,c.Ld=K.Yd.link.stream):8192===(c.mode&61440)&&(c.Kd=K.Yd.Je.node,c.Ld=K.Yd.Je.stream);c.timestamp=Date.now();a&&(a.Jd[b]=c);return c},If:function(a){if(a.Jd&&a.Jd.subarray){for(var b=[],c=0;c<a.Md;++c)b.push(a.Jd[c]);return b}return a.Jd},Jf:function(a){return a.Jd?
a.Jd.subarray?a.Jd.subarray(0,a.Md):new Uint8Array(a.Jd):new Uint8Array(0)},Le:function(a,b){var c=a.Jd?a.Jd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Jd,a.Jd=new Uint8Array(b),0<a.Md&&a.Jd.set(c.subarray(0,a.Md),0))},wf:function(a,b){if(a.Md!=b)if(0==b)a.Jd=null,a.Md=0;else{if(!a.Jd||a.Jd.subarray){var c=a.Jd;a.Jd=new Uint8Array(b);c&&a.Jd.set(c.subarray(0,Math.min(b,a.Md)))}else if(a.Jd||(a.Jd=[]),a.Jd.length>b)a.Jd.length=b;else for(;a.Jd.length<b;)a.Jd.push(0);
a.Md=b}},Kd:{ae:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Md:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bf=4096;b.blocks=Math.ceil(b.size/b.bf);return b},Rd:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&K.wf(a,b.size)},lookup:function(){throw Db[44];},pe:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Eb(b,c)}catch(f){}if(d)for(var e in d.Jd)throw new J(55);}delete a.parent.Jd[a.name];a.name=c;b.Jd[c]=a;a.parent=b},unlink:function(a,b){delete a.Jd[b]},rmdir:function(a,b){var c=Eb(a,b),d;for(d in c.Jd)throw new J(55);delete a.Jd[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Jd)a.Jd.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},Ld:{read:function(a,b,c,d,e){var f=a.node.Jd;if(e>=a.node.Md)return 0;a=Math.min(a.node.Md-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Jd||a.Jd.subarray)){if(f)return a.Jd=b.subarray(c,c+d),a.Md=d;if(0===a.Md&&0===e)return a.Jd=
b.slice(c,c+d),a.Md=d;if(e+d<=a.Md)return a.Jd.set(b.subarray(c,c+d),e),d}K.Le(a,e+d);if(a.Jd.subarray&&b.subarray)a.Jd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Jd[e+f]=b[c+f];a.Md=Math.max(a.Md,e+d);return d},ce:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Md);if(0>b)throw new J(28);return b},Fe:function(a,b,c){K.Le(a.node,b+c);a.node.Md=Math.max(a.node.Md,b+c)},Te:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.Jd;
if(f&2||a.buffer!==Na){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=H(f);c<f;)w[b+c++]=0;c=b;if(!c)throw new J(48);w.set(a,c)}else d=!1,c=a.byteOffset;return{Qf:c,Cf:d}},Ve:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.Ld.write(a,b,0,d,c,!1);return 0}}},Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Kb=!0,Lb={},J=null,Db={};
function Mb(a,b){a=ub("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Me:!0,Ae:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ae)throw new J(32);a=pb(a.split("/").filter(function(g){return!!g}),!1);var e=Fb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Eb(e,a[d]);c=qb(c+"/"+a[d]);e.ke&&(!f||f&&b.Me)&&(e=e.ke.root);if(!f||b.ve)for(f=0;40960===(e.mode&61440);)if(e=Nb(c),c=ub(rb(c),e),e=Mb(c,{Ae:b.Ae}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.Zd.Ue,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Eb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.Kd.lookup?0:2)throw new J(c,a);for(c=Jb[Pb(a.id,b)];c;c=c.ee){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Kd.lookup(a,b)}
function Cb(a,b,c,d){a=new Rb(a,b,c,d);b=Pb(a.parent.id,a.name);a.ee=Jb[b];return Jb[b]=a}var Sb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ub(a,b){try{return Eb(a,b),20}catch(c){}return Qb(a,"wx")}
function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Hb[a])return a;throw new J(33);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={});var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Hb[b]=a}var Bb={open:function(a){a.Ld=Gb[a.node.rdev].Ld;a.Ld.open&&a.Ld.open(a)},ce:function(){throw new J(70);}};function xb(a,b){Gb[a]={Ld:b}}
function Yb(a,b){var c="/"===b,d=!b;if(c&&Fb)throw new J(10);if(!c&&!d){var e=Mb(b,{Me:!1});b=e.path;e=e.node;if(e.ke)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,Pf:{},Ue:b,tf:[]};a=a.Zd(b);a.Zd=b;b.root=a;c?Fb=a:e&&(e.ke=b,e.Zd&&e.Zd.tf.push(b))}function Zb(a,b,c){var d=Mb(a,{parent:!0}).node;a=sb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Ub(d,a);if(e)throw new J(e);if(!d.Kd.pe)throw new J(63);return d.Kd.pe(d,a,b,c)}function M(a){Zb(a,16895,0)}
function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function ac(a,b){if(!ub(a))throw new J(44);var c=Mb(b,{parent:!0}).node;if(!c)throw new J(44);b=sb(b);var d=Ub(c,b);if(d)throw new J(d);if(!c.Kd.symlink)throw new J(63);c.Kd.symlink(c,b,a)}
function bc(a){var b=Mb(a,{parent:!0}).node,c=sb(a),d=Eb(b,c);a:{try{var e=Eb(b,c)}catch(g){e=g.Xd;break a}var f=Qb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new J(e);if(!b.Kd.unlink)throw new J(63);if(d.ke)throw new J(10);try{Lb.willDeletePath&&Lb.willDeletePath(a)}catch(g){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.Kd.unlink(b,c);b=Pb(d.parent.id,d.name);if(Jb[b]===d)Jb[b]=d.ee;else for(b=Jb[b];b;){if(b.ee===d){b.ee=d.ee;break}b=b.ee}try{if(Lb.onDeletePath)Lb.onDeletePath(a)}catch(g){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+g.message)}}function Nb(a){a=Mb(a).node;if(!a)throw new J(44);if(!a.Kd.readlink)throw new J(28);return ub(Ob(a.parent),a.Kd.readlink(a))}function cc(a,b){var c;"string"===typeof a?c=Mb(a,{ve:!0}).node:c=a;if(!c.Kd.Rd)throw new J(63);c.Kd.Rd(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function dc(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=qb(a);try{f=Mb(a,{ve:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Zb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Tb(b)||b&512)?31:Qb(f,Tb(b)):44))throw new J(c);if(b&512){c=f;var g;"string"===typeof c?g=Mb(c,{ve:!0}).node:g=c;if(!g.Kd.Rd)throw new J(63);if(16384===(g.mode&61440))throw new J(31);if(32768!==(g.mode&61440))throw new J(28);if(c=Qb(g,"w"))throw new J(c);g.Kd.Rd(g,{size:0,timestamp:Date.now()})}b&=-131713;d=Wb({node:f,path:Ob(f),flags:b,seekable:!0,position:0,Ld:f.Ld,zf:[],error:!1},d);d.Ld.open&&d.Ld.open(d);!h.logReadFiles||b&1||(ec||(ec={}),a in ec||(ec[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Lb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Lb.onOpenFile(a,f))}catch(m){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function fc(a){if(null===a.fd)throw new J(8);a.we&&(a.we=null);try{a.Ld.close&&a.Ld.close(a)}catch(b){throw b;}finally{Hb[a.fd]=null}a.fd=null}
function hc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.Ld.ce)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.Ld.ce(a,b,c);a.zf=[]}
function ic(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.Ld.write)throw new J(28);a.seekable&&a.flags&1024&&hc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new J(70);b=a.Ld.write(a,b,c,d,e,f);g||(a.position+=b);try{if(a.path&&Lb.onWriteToFile)Lb.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
m.message)}return b}function jc(){J||(J=function(a,b){this.node=b;this.xf=function(c){this.Xd=c};this.xf(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){Db[a]=new J(a);Db[a].stack="<generic error, no stack>"}))}var kc;function lc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function mc(a,b){a="string"===typeof a?a:Ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=qb(a+"/"+c);try{M(d)}catch(e){}a=d}}return d}
function nc(a,b,c,d){a=qb(("string"===typeof a?a:Ob(a))+"/"+b);c=lc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}function oc(a,b,c,d,e,f){a=b?qb(("string"===typeof a?a:Ob(a))+"/"+b):a;d=lc(d,e);e=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}cc(e,d|146);a=dc(e,577);ic(a,c,0,c.length,0,f);fc(a);cc(e,d)}return e}
function N(a,b,c,d){a=qb(("string"===typeof a?a:Ob(a))+"/"+b);b=lc(!!c,!!d);N.Re||(N.Re=64);var e=N.Re++<<8|0;xb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var q=0,p=0;p<n;p++){try{var t=c()}catch(u){throw new J(29);}if(void 0===t&&0===q)throw new J(6);if(null===t||void 0===t)break;q++;g[m+p]=t}q&&(f.node.timestamp=Date.now());return q},write:function(f,g,m,n){for(var q=0;q<n;q++)try{d(g[m+q])}catch(p){throw new J(29);}n&&(f.node.timestamp=
Date.now());return q}});return $b(a,b,e)}function qc(a){if(!(a.rf||a.sf||a.link||a.Jd)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Jd=ib(ka(a.url),!0),a.Md=a.Jd.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function rc(a,b,c,d,e){function f(){this.xe=!1;this.Od=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.Pe(p/this.chunkSize|0)[t]}};f.prototype.he=function(p){this.Pe=p};f.prototype.He=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),u,v=(u=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;p=(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;v||(z=t);var B=this;B.he(function(F){var ta=F*z,ma=(F+1)*z-1;ma=Math.min(ma,t-1);if("undefined"===typeof B.Od[F]){var pc=B.Od;if(ta>ma)throw Error("invalid range ("+ta+", "+ma+") or no bytes requested!");if(ma>t-1)throw Error("only "+t+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);t!==z&&L.setRequestHeader("Range","bytes="+ta+"-"+ma);"undefined"!=typeof Uint8Array&&(L.responseType=
"arraybuffer");L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);ta=void 0!==L.response?new Uint8Array(L.response||[]):ib(L.responseText||"",!0);pc[F]=ta}if("undefined"===typeof B.Od[F])throw Error("doXHR failed!");return B.Od[F]});if(p||!t)z=t=1,z=t=this.Pe(0).length,sa("LazyFiles on gzip forces download of the whole file when length is accessed");this.af=
t;this.$e=z;this.xe=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.xe||this.He();return this.af}},chunkSize:{get:function(){this.xe||this.He();return this.$e}}});var m=void 0}else m=c,g=void 0;var n=nc(a,b,d,e);g?n.Jd=g:m&&(n.Jd=null,n.url=m);Object.defineProperties(n,{Md:{get:function(){return this.Jd.length}}});
var q={};Object.keys(n.Ld).forEach(function(p){var t=n.Ld[p];q[p]=function(){qc(n);return t.apply(null,arguments)}});q.read=function(p,t,u,v,z){qc(n);p=p.node.Jd;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var B=0;B<v;B++)t[u+B]=p[z+B];else for(B=0;B<v;B++)t[u+B]=p.get(z+B);return v};n.Ld=q;return n}
function sc(a,b,c,d,e,f,g,m,n,q){function p(v){function z(F){q&&q();m||oc(a,b,F,d,e,n);f&&f();bb(u)}var B=!1;h.preloadPlugins.forEach(function(F){!B&&F.canHandle(t)&&(F.handle(v,t,z,function(){g&&g();bb(u)}),B=!0)});B||z(v)}tc();var t=b?ub(qb(a+"/"+b)):a,u="cp "+t;ab(u);"string"==typeof c?uc(c,function(v){p(v)},g):p(c)}var vc={},Xb,ec,wc=void 0;function xc(){wc+=4;return x[wc-4>>2]}function yc(a){a=Hb[a];if(!a)throw new J(8);return a}var zc;
ia?zc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?zc=dateNow:zc=function(){return performance.now()};
function Ac(a,b){Bc=a;Cc=b;if(Dc)if(0==a)Ec=function(){var d=Math.max(0,Fc+b-zc())|0;setTimeout(Gc,d)};else if(1==a)Ec=function(){Hc(Gc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Ec=function(){setImmediate(Gc)}}}
function Ic(a,b,c,d,e){noExitRuntime=!0;assert(!Dc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Dc=a;Jc=d;var f=Kc;Gc=function(){if(!Ba)if(0<Lc.length){var g=Date.now(),m=Lc.shift();m.Ne(m.me);if(Mc){var n=Mc,q=0==n%1?n-1:Math.floor(n);Mc=m.Ef?q:(8*n+(q+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||
"Please wait...",m=Mc,n=Nc.Gf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<Kc||setTimeout(Gc,0)}else if(!(f<Kc))if(Oc=Oc+1|0,1==Bc&&1<Cc&&0!=Oc%Cc)Ec();else{0==Bc&&(Fc=zc());a:if(!(Ba||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(p){if(p instanceof ra||"unwind"==p)break a;p&&"object"===typeof p&&p.stack&&k("exception thrown: "+[p,p.stack]);throw p;}h.postMainLoop&&h.postMainLoop()}f<Kc||("object"===typeof SDL&&SDL.audio&&SDL.audio.vf&&SDL.audio.vf(),Ec())}};e||
(b&&0<b?Ac(0,1E3/b):Ac(1,1),Ec());if(c)throw"unwind";}var Ec=null,Kc=0,Dc=null,Jc=0,Bc=0,Cc=0,Oc=0,Lc=[],Nc={},Fc,Gc,Mc,Pc=!1,Qc=!1,Rc=[];
function tc(){function a(){Qc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!Sc){Sc=!0;try{Tc=!0}catch(c){Tc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Uc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Tc?null:console.log("warning: no BlobBuilder");
Vc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.We||"undefined"!==typeof Vc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.We=!0);h.preloadPlugins.push({canHandle:function(c){return!h.We&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(Tc)try{g=new Blob([c],{type:Wc(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Wc(d)}))}catch(q){ua("Blob constructor present but fails: "+
q+"; falling back to blob builder")}g||(g=new Uc,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=Vc.createObjectURL(g),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=q;Vc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.Of&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(Tc){try{var q=new Blob([c],{type:Wc(d)})}catch(t){return m()}q=Vc.createObjectURL(q);var p=new Audio;p.addEventListener("canplaythrough",function(){g(p)},!1);p.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,
z=0;z<c.length;z++)for(u=u<<8|c[z],v+=8;6<=v;){var B=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(p)}};p.src=q;Xc(function(){g(p)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&
b.addEventListener("click",function(c){!Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Yc(a,b,c,d){if(b&&h.Wd&&a==h.canvas)return h.Wd;var e;if(b){var f={antialias:!1,alpha:!1,Se:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof Zc&&(e=$c(a,f)))var m=ad[e].$d}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof O,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.Wd=m,b&&bd(e),h.Af=b,Rc.forEach(function(n){n()}),tc());return m}var cd=!1,dd=void 0,ed=void 0;
function fd(a,b){function c(){Pc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=gd,dd&&d.requestPointerLock(),Pc=!0,ed?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=Pa[SDL.screen>>2]|8388608),hd(h.canvas),id()):hd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),ed?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=Pa[SDL.screen>>2]&
-8388609),hd(h.canvas),id()):hd(d));if(h.onFullScreen)h.onFullScreen(Pc);if(h.onFullscreen)h.onFullscreen(Pc)}dd=a;ed=b;"undefined"===typeof dd&&(dd=!0);"undefined"===typeof ed&&(ed=!1);var d=h.canvas;cd||(cd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function gd(){if(!Pc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var jd=0;function Hc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jd)jd=b+1E3/60;else for(;b+2>=jd;)jd+=1E3/60;setTimeout(a,Math.max(jd-b,0))}}function Xc(a){noExitRuntime=!0;setTimeout(function(){Ba||a()},1E4)}
function Wc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function uc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&bb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&ab(d)}var kd=[];function id(){var a=h.canvas;kd.forEach(function(b){b(a.width,a.height)})}
function hd(a,b,c){b&&c?(a.Bf=b,a.lf=c):(b=a.Bf,c=a.lf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}ed?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Sc,Tc,Uc,Vc,P=12288,ld=!1,md=0,nd=0,od=0,Q={alpha:!1,depth:!1,stencil:!1,antialias:!1},pd={},qd;function rd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function sd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function td(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var ud=1,vd=[],R=[],wd=[],xd=[],yd=[],S=[],T=[],zd=[],ad=[],U=[],Ad={},Bd={},Cd=4;
function V(a){Dd||(Dd=a)}function Ed(a){for(var b=ud++,c=a.length;c<b;c++)a[c]=null;return b}function $c(a,b){if(a=a.getContext("webgl",b)){var c=Ed(ad),d={Kf:c,attributes:b,version:b.Se,$d:a};a.canvas&&(a.canvas.ge=d);ad[c]=d;("undefined"===typeof b.gf||b.gf)&&Fd(d);b=c}else b=0;return b}function bd(a){Gd=ad[a];h.Wd=O=Gd&&Gd.$d}
function Fd(a){a||(a=Gd);if(!a.nf){a.nf=!0;var b=a.$d;rd(b);sd(b);td(b);b.Ud=b.getExtension("EXT_disjoint_timer_query");b.Nf=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Zc={},Dd,Gd,Hd=0;function Id(){for(var a=Jd.length-1;0<=a;--a)Kd(a);Jd=[];W=[]}var W=[];function Ld(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in W){var f=W[e];if(f.Ce==a&&d(f.Ge,c))return}W.push({Ce:a,Xe:b,Ge:c});W.sort(function(g,m){return g.Xe<m.Xe})}function Md(a){for(var b=0;b<W.length;++b)W[b].Ce==a&&(W.splice(b,1),--b)}
function Nd(){if(Hd&&Od.be)for(var a=0;a<W.length;++a){var b=W[a];W.splice(a,1);--a;b.Ce.apply(null,b.Ge)}}var Jd=[];function Kd(a){var b=Jd[a];b.target.removeEventListener(b.Pd,b.hf,b.Sd);Jd.splice(a,1)}function X(a){function b(d){++Hd;Od=a;Nd();a.Vd(d);Nd();--Hd}if(a.Td)a.hf=b,a.target.addEventListener(a.Pd,b,a.Sd),Jd.push(a),Pd||(Va.push(Id),Pd=!0);else for(var c=0;c<Jd.length;++c)Jd[c].target==a.target&&Jd[c].Pd==a.Pd&&Kd(c--)}
function Qd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Rd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Sd={},Pd,Od,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee={},fe=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Y(a){a=2<a?E(a):a;return fe[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function ge(a){var b=Fa(),c=Ea(8),d=c+4,e=Ea(a.id.length+1);D(a.id,e,a.id.length+1);if(a=Y(e))x[c>>2]=a.width,x[d>>2]=a.height;c=[x[c>>2],x[d>>2]];Ga(b);return c}function he(a,b,c){a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0}function ie(a,b,c){if(a.Df){var d=Fa(),e=Ea(a.id.length+1);D(a.id,e,a.id.length+1);he(e,b,c);Ga(d)}else a.width=b,a.height=c}
function je(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ie(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=B,a.style.marginBottom=F,document.body.style.margin=ta,document.documentElement.style.overflow=ma,document.body.scroll=pc,a.style.Qe=L,a.ge&&a.ge.$d.viewport(0,0,d,e),ee.ne&&I.get(ee.ne)(37,0,ee.Ie))}var c=ge(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,B=a.style.marginTop,F=a.style.marginBottom,
ta=document.body.style.margin,ma=document.documentElement.style.overflow,pc=document.body.scroll,L=a.style.Qe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ke(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function le(a){return 0>fe.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function me(a,b){if(0!=b.Be||0!=b.se){je(a);var c=b.yf?innerWidth:screen.width,d=b.yf?innerHeight:screen.height,e=le(a),f=e.width;e=e.height;var g=ge(a),m=g[0];g=g[1];3==b.Be?(ke(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Be&&(c*g<m*d?(f=g*c/m,ke(a,(d-f)/2,0),d=f):(f=m*d/g,ke(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.jf&&(a.style.Qe="pixelated");
f=2==b.se?devicePixelRatio:1;0!=b.se&&(c=c*f|0,d=d*f|0,ie(a,c,d),a.ge&&a.ge.$d.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Rd()?-3:-1;ee=b;b.ne&&I.get(b.ne)(37,0,b.Ie);return 0}function ne(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.qe)a.qe();else return document.body.requestPointerLock||document.body.qe?-3:-1;return 0}
function oe(a,b){C[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)C[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)C[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;D(b.id,a+1304,64);D(b.mapping,a+1368,64)}var pe=[];
function qe(a,b,c,d){for(var e=0;e<a;e++){var f=O[c](),g=f&&Ed(d);f?(f.name=g,d[g]=f):V(1282);x[b+4*e>>2]=g}}function re(a,b,c,d,e,f,g,m){b=R[b];if(a=O[a](b,c))d=m&&D(a.name,m,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),g&&(x[g>>2]=a.type)}function se(a,b){Pa[a>>2]=b;Pa[a+4>>2]=(b-Pa[a>>2])/4294967296}
function te(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 36345:d=0;break;case 34466:var e=O.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=O.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:w[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:se(b,
d);break;case 0:x[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:w[b>>0]=d?1:0}}else V(1281)}function ue(a){var b=Ka(a)+1,c=H(b);D(a,c,b);return c}function ve(a,b,c,d){if(c)if(a=O.getUniform(R[a],S[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else V(1281)}
function we(a,b,c,d){if(c)if(a=O.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else V(1281)}
function xe(a,b,c,d,e){a-=5120;a=1==a?G:4==a?x:6==a?A:5==a||28922==a?Pa:Oa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Cd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var ye=[],ze=[];function Ae(a,b){if(!Rd())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Hd&&Od.be?me(a,b):b.ff?(Ld(me,1,[a,b]),1):-2:-3:-4}
function Be(a,b){var c={target:Y(2),Pd:"beforeunload",Td:b,Vd:function(d){d=d||event;var e=I.get(b)(28,0,a);e&&(e=E(e));if(e)return d.preventDefault(),d.returnValue=e},Sd:!0};X(c)}function Ce(a,b,c,d,e,f){Ud||(Ud=H(256));a={target:Y(a),Pd:f,Td:d,Vd:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Ud;D(Qd(g.target),n+0,128);D(m,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},Sd:c};X(a)}
function De(a,b,c,d,e){Wd||(Wd=H(280));X({target:a,Pd:e,Td:d,Vd:function(f){f=f||event;var g=Wd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;x[g>>2]=n;x[g+4>>2]=Rd();var q=n?m:Vd,p=q&&q.id?q.id:"";D(Qd(q),g+8,128);D(p,g+136,128);x[g+264>>2]=q?q.clientWidth:0;x[g+268>>2]=q?q.clientHeight:0;x[g+272>>2]=screen.width;x[g+276>>2]=screen.height;n&&(Vd=m);I.get(d)(19,g,b)&&f.preventDefault()},Sd:c})}
function Ee(a,b,c,d,e){Xd||(Xd=H(1432));b={target:Y(2),be:!0,Pd:e,Td:c,Vd:function(f){f=f||event;var g=Xd;oe(g,f.gamepad);I.get(c)(d,g,a)&&f.preventDefault()},Sd:b};X(b)}
function Fe(a,b,c,d,e,f){Yd||(Yd=H(164));a={target:Y(a),be:!0,Pd:f,Td:d,Vd:function(g){var m=Yd,n=m>>2;x[n]=g.location;x[n+1]=g.ctrlKey;x[n+2]=g.shiftKey;x[n+3]=g.altKey;x[n+4]=g.metaKey;x[n+5]=g.repeat;x[n+6]=g.charCode;x[n+7]=g.keyCode;x[n+8]=g.which;D(g.key||"",m+36,32);D(g.code||"",m+68,32);D(g.char||"",m+100,32);D(g.locale||"",m+132,32);I.get(d)(e,m,b)&&g.preventDefault()},Sd:c};X(a)}
function Ge(a,b,c){a>>=2;x[a]=b.screenX;x[a+1]=b.screenY;x[a+2]=b.clientX;x[a+3]=b.clientY;x[a+4]=b.ctrlKey;x[a+5]=b.shiftKey;x[a+6]=b.altKey;x[a+7]=b.metaKey;ya[2*a+16]=b.button;ya[2*a+17]=b.buttons;x[a+9]=b.movementX;x[a+10]=b.movementY;c=le(c);x[a+11]=b.clientX-c.left;x[a+12]=b.clientY-c.top}function He(a,b,c,d,e,f){Zd||(Zd=H(64));a=Y(a);X({target:a,be:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Pd:f,Td:d,Vd:function(g){g=g||event;Ge(Zd,g,a);I.get(d)(e,Zd,b)&&g.preventDefault()},Sd:c})}
function Ie(a,b,c,d,e){$d||($d=H(260));X({target:a,Pd:e,Td:d,Vd:function(f){f=f||event;var g=$d,m=document.pointerLockElement||document.he||document.Ee||document.De;x[g>>2]=!!m;var n=m&&m.id?m.id:"";D(Qd(m),g+4,128);D(n,g+132,128);I.get(d)(20,g,b)&&f.preventDefault()},Sd:c})}
function Je(a,b,c,d){ae||(ae=H(36));a=Y(a);X({target:a,Pd:"resize",Td:d,Vd:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=ae;x[g>>2]=e.detail;x[g+4>>2]=f.clientWidth;x[g+8>>2]=f.clientHeight;x[g+12>>2]=innerWidth;x[g+16>>2]=innerHeight;x[g+20>>2]=outerWidth;x[g+24>>2]=outerHeight;x[g+28>>2]=pageXOffset;x[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},Sd:c})}
function Ke(a,b,c,d,e,f){be||(be=H(1684));a=Y(a);X({target:a,be:"touchstart"==f||"touchend"==f,Pd:f,Td:d,Vd:function(g){for(var m={},n=g.touches,q=0;q<n.length;++q){var p=n[q];m[p.identifier]=p}n=g.changedTouches;for(q=0;q<n.length;++q)p=n[q],p.qf=1,m[p.identifier]=p;n=g.targetTouches;for(q=0;q<n.length;++q)m[n[q].identifier].uf=1;n=be;p=n>>2;x[p+1]=g.ctrlKey;x[p+2]=g.shiftKey;x[p+3]=g.altKey;x[p+4]=g.metaKey;p+=5;var t=le(a),u=0;for(q in m){var v=m[q];x[p]=v.identifier;x[p+1]=v.screenX;x[p+2]=v.screenY;
x[p+3]=v.clientX;x[p+4]=v.clientY;x[p+5]=v.pageX;x[p+6]=v.pageY;x[p+7]=v.qf;x[p+8]=v.uf;x[p+9]=v.clientX-t.left;x[p+10]=v.clientY-t.top;p+=13;if(31<++u)break}x[n>>2]=u;I.get(d)(e,n,b)&&g.preventDefault()},Sd:c})}function Le(a,b,c){var d=fe[1];ce||(ce=H(8));X({target:d,Pd:"visibilitychange",Td:c,Vd:function(e){e=e||event;var f=ce,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[f>>2]=document.hidden;x[f+4>>2]=g;I.get(c)(21,f,a)&&e.preventDefault()},Sd:b})}
function Me(a,b,c,d){de||(de=H(96));X({target:a,be:!0,Pd:"wheel",Td:d,Vd:function(e){e=e||event;var f=de;Ge(f,e,a);C[f+64>>3]=e.deltaX;C[f+72>>3]=e.deltaY;C[f+80>>3]=e.deltaZ;x[f+88>>2]=e.deltaMode;I.get(d)(9,f,b)&&e.preventDefault()},Sd:c})}var Ne={};
function Oe(){if(!Pe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ne)a[b]=Ne[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pe=c}return Pe}var Pe,Qe=[];function Rb(a,b,c,d){a||(a=this);this.parent=a;this.Zd=a.Zd;this.ke=null;this.id=Ib++;this.name=b;this.mode=c;this.Kd={};this.Ld={};this.rdev=d}
Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sf:{get:function(){return 16384===(this.mode&61440)}},rf:{get:function(){return 8192===(this.mode&61440)}}});jc();Jb=Array(4096);Yb(K,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");xb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});$b("/dev/null",259);wb(1280,zb);wb(1536,Ab);$b("/dev/tty",1280);$b("/dev/tty1",1536);var a=tb();N("/dev","random",a);N("/dev","urandom",a);M("/dev/shm");M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");
Yb({Zd:function(){var a=Cb("/proc/self","fd",16895,73);a.Kd={lookup:function(b,c){var d=Hb[+c];if(!d)throw new J(8);b={parent:null,Zd:{Ue:"fake"},Kd:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");h.FS_createPath=mc;h.FS_createDataFile=oc;h.FS_createPreloadedFile=sc;h.FS_createLazyFile=rc;h.FS_createDevice=N;h.FS_unlink=bc;h.requestFullscreen=function(a,b){fd(a,b)};h.requestAnimationFrame=function(a){Hc(a)};
h.setCanvasSize=function(a,b,c){hd(h.canvas,a,b);c||id()};h.pauseMainLoop=function(){Ec=null;Kc++};h.resumeMainLoop=function(){Kc++;var a=Bc,b=Cc,c=Dc;Dc=null;Ic(c,0,!1,Jc,!0);Ac(a,b);Ec()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Yc(a,b,c,d)};for(var O,Z=0;32>Z;++Z)pe.push(Array(Z));var Re=new Float32Array(288);
for(Z=0;288>Z;++Z)ye[Z]=Re.subarray(0,Z+1);var Se=new Int32Array(288);for(Z=0;288>Z;++Z)ze[Z]=Se.subarray(0,Z+1);function ib(a,b){var c=Array(Ka(a)+1);a=Ja(a,c,0,c.length);b&&(c.length=a);return c}Ta.push({Ne:function(){Te()}});
var Ve={n:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 0:var e=xc();return 0>e?-28:dc(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=xc(),d.flags|=e,0;case 12:return e=xc(),ya[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return nb(),-1;default:return-28}}catch(f){return"undefined"!==typeof vc&&f instanceof J||r(f),-f.Xd}},wa:function(a,b,c){wc=c;try{var d=yc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=xc();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=xc();if(!d.Ld.pf)throw new J(59);return d.Ld.pf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:r("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof vc&&f instanceof J||r(f),-f.Xd}},xa:function(a,b,c){wc=c;try{var d=E(a),e=xc();return dc(d,b,e).fd}catch(f){return"undefined"!==typeof vc&&f instanceof J||r(f),-f.Xd}},h:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=zc();else return nb(),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},Ba:function(){r("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Zc:function(a){if(12448==a)return P=12288,1;P=12300;return 0},ta:function(a,b,c,d,e){if(62E3!=a)P=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)Q.alpha=0<x[b+4>>2];else if(12325==a)Q.depth=0<x[b+4>>2];else if(12326==a)Q.stencil=0<x[b+4>>2];else if(12337==a)a=
x[b+4>>2],Q.antialias=0<a;else if(12338==a)a=x[b+4>>2],Q.antialias=1==a;else if(12544==a)Q.Lf=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),P=12288,c=1):(P=12300,c=0)}return c},fb:function(a,b,c,d){if(62E3!=a)return P=12296,0;for(a=1;;){b=x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return P=12292,0;d+=8}if(2!=a)return P=12293,0;Q.Se=a-1;Q.Mf=0;qd=$c(h.canvas,Q);if(0!=qd)return P=12288,bd(qd),h.Af=!0,Rc.forEach(function(e){e()}),bd(null),
62004;P=12297;return 0},Cb:function(a,b){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;P=12288;return 62006},qb:function(a,b){if(62E3!=a)return P=12296,0;if(62004!=b)return P=12294,0;a=qd;Gd===ad[a]&&(Gd=null);if("object"===typeof Sd)for(var c=ad[a].$d.canvas,d=0;d<Jd.length;++d)Jd[d].target!=c||Kd(d--);ad[a]&&ad[a].$d.canvas&&(ad[a].$d.canvas.ge=void 0);ad[a]=null;P=12288;md==b&&(md=0);return 1},Nb:function(a,b){if(62E3!=a)return P=12296,0;if(62006!=b)return P=12301,1;nd==b&&(nd=0);od==
b&&(od=0);P=12288;return 1},za:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(62002!=b)return P=12293,0;if(!d)return P=12300,0;P=12288;switch(c){case 12320:return x[d>>2]=Q.alpha?32:24,1;case 12321:return x[d>>2]=Q.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>2]=8,1;case 12324:return x[d>>2]=8,1;case 12325:return x[d>>2]=Q.depth?24:0,1;case 12326:return x[d>>2]=Q.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>
2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>2]=12344,1;case 12337:return x[d>>2]=Q.antialias?4:0,1;case 12338:return x[d>>2]=Q.antialias?1:0,1;case 12339:return x[d>>2]=4,1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>
2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return P=12292,0}},O:function(){P=12288;return 62E3},Wa:function(){return P},id:function(a){return Ue(a)},Z:function(a,b,c){if(62E3==a)return b&&(x[b>>2]=1),c&&(x[c>>2]=4),ld=!0,P=12288,1;P=12296;return 0},Yb:function(a,b,c,d){if(62E3!=a)return P=12296,0;if(0!=d&&62004!=d)return P=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return P=12301,0;bd(d?qd:null);md=d;od=b;nd=c;P=12288;return 1},La:function(a,
b){if(62E3!=a)return P=12296,0;P=12288;if(pd[b])return pd[b];switch(b){case 12371:a=La("Emscripten");break;case 12372:a=La("1.4 Emscripten EGL");break;case 12373:a=La("");break;case 12429:a=La("OpenGL_ES");break;default:return P=12300,0}return pd[b]=a},hc:function(){if(ld)if(h.Wd)if(h.Wd.isContextLost())P=12302;else return P=12288,1;else P=12290;else P=12289;return 0},sc:function(a,b){if(62E3!=a)return P=12296,0;0==b?Ac(0,0):Ac(1,b);P=12288;return 1},ia:function(a){if(62E3!=a)return P=12296,0;od=
nd=md=0;ld=!1;P=12288;return 1},Oc:function(){P=12288;return 1},Dc:function(){P=12288;return 1},b:function(a,b,c){Qe.length=0;var d;for(c>>=2;d=G[b++];)(d=105>d)&&c&1&&c++,Qe.push(d?C[c++>>1]:x[c]),++c;return kb[a].apply(null,Qe)},Ca:function(){if(!Rd())return-1;Md(me);var a=fe[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Fa:function(){Md(ne);if(document.exitPointerLock)document.exitPointerLock();
else if(document.Od)document.Od();else return-1;return 0},f:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},d:function(a,b,c){a=Y(a);if(!a)return-4;a=le(a);C[b>>3]=a.width;C[c>>3]=a.height;return 0},q:function(a,b){if(0>a||a>=Td.length)return-5;if(!Td[a])return-7;oe(b,Td[a]);return 0},Aa:function(){return Td.length},W:function(a){O.activeTexture(a)},V:function(a,b){O.attachShader(R[a],T[b])},ma:function(a,b){O.Ud.beginQueryEXT(a,U[b])},U:function(a,b,c){O.bindAttribLocation(R[a],
b,E(c))},T:function(a,b){O.bindBuffer(a,vd[b])},S:function(a,b){O.bindFramebuffer(a,wd[b])},R:function(a,b){O.bindRenderbuffer(a,xd[b])},Q:function(a,b){O.bindTexture(a,yd[b])},da:function(a){O.bindVertexArray(zd[a])},P:function(a,b,c,d){O.blendColor(a,b,c,d)},sd:function(a){O.blendEquation(a)},rd:function(a,b){O.blendEquationSeparate(a,b)},qd:function(a,b){O.blendFunc(a,b)},pd:function(a,b,c,d){O.blendFuncSeparate(a,b,c,d)},od:function(a,b,c,d){O.bufferData(a,c?G.subarray(c,c+b):b,d)},nd:function(a,
b,c,d){O.bufferSubData(a,b,G.subarray(d,d+c))},md:function(a){return O.checkFramebufferStatus(a)},ld:function(a){O.clear(a)},kd:function(a,b,c,d){O.clearColor(a,b,c,d)},jd:function(a){O.clearDepth(a)},hd:function(a){O.clearStencil(a)},gd:function(a,b,c,d){O.colorMask(!!a,!!b,!!c,!!d)},fd:function(a){O.compileShader(T[a])},ed:function(a,b,c,d,e,f,g,m){O.compressedTexImage2D(a,b,c,d,e,f,m?G.subarray(m,m+g):null)},dd:function(a,b,c,d,e,f,g,m,n){O.compressedTexSubImage2D(a,b,c,d,e,f,g,n?G.subarray(n,
n+m):null)},cd:function(a,b,c,d,e,f,g,m){O.copyTexImage2D(a,b,c,d,e,f,g,m)},bd:function(a,b,c,d,e,f,g,m){O.copyTexSubImage2D(a,b,c,d,e,f,g,m)},ad:function(){var a=Ed(R),b=O.createProgram();b.name=a;R[a]=b;return a},$c:function(a){var b=Ed(T);T[b]=O.createShader(a);return b},_c:function(a){O.cullFace(a)},Yc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=vd[d];e&&(O.deleteBuffer(e),e.name=0,vd[d]=null)}},Xc:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=wd[d];e&&(O.deleteFramebuffer(e),
e.name=0,wd[d]=null)}},Wc:function(a){if(a){var b=R[a];b?(O.deleteProgram(b),b.name=0,R[a]=null,Ad[a]=null):V(1281)}},oa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=U[d];e&&(O.Ud.deleteQueryEXT(e),U[d]=null)}},Vc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=xd[d];e&&(O.deleteRenderbuffer(e),e.name=0,xd[d]=null)}},Uc:function(a){if(a){var b=T[a];b?(O.deleteShader(b),T[a]=null):V(1281)}},Tc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=yd[d];e&&(O.deleteTexture(e),e.name=
0,yd[d]=null)}},ca:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];O.deleteVertexArray(zd[d]);zd[d]=null}},Sc:function(a){O.depthFunc(a)},Rc:function(a){O.depthMask(!!a)},Qc:function(a,b){O.depthRange(a,b)},Pc:function(a,b){O.detachShader(R[a],T[b])},Nc:function(a){O.disable(a)},Mc:function(a){O.disableVertexAttribArray(a)},Lc:function(a,b,c){O.drawArrays(a,b,c)},_:function(a,b,c,d){O.drawArraysInstanced(a,b,c,d)},$:function(a,b){for(var c=pe[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];O.drawBuffers(c)},
Kc:function(a,b,c,d){O.drawElements(a,b,c,d)},Y:function(a,b,c,d,e){O.drawElementsInstanced(a,b,c,d,e)},Jc:function(a){O.enable(a)},Ic:function(a){O.enableVertexAttribArray(a)},la:function(a){O.Ud.endQueryEXT(a)},Hc:function(){O.finish()},Gc:function(){O.flush()},Fc:function(a,b,c,d){O.framebufferRenderbuffer(a,b,c,xd[d])},Ec:function(a,b,c,d,e){O.framebufferTexture2D(a,b,c,yd[d],e)},Cc:function(a){O.frontFace(a)},Bc:function(a,b){qe(a,b,"createBuffer",vd)},zc:function(a,b){qe(a,b,"createFramebuffer",
wd)},pa:function(a,b){for(var c=0;c<a;c++){var d=O.Ud.createQueryEXT();if(!d){for(V(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Ed(U);d.name=e;U[e]=d;x[b+4*c>>2]=e}},yc:function(a,b){qe(a,b,"createRenderbuffer",xd)},xc:function(a,b){qe(a,b,"createTexture",yd)},ba:function(a,b){qe(a,b,"createVertexArray",zd)},Ac:function(a){O.generateMipmap(a)},wc:function(a,b,c,d,e,f,g){re("getActiveAttrib",a,b,c,d,e,f,g)},vc:function(a,b,c,d,e,f,g){re("getActiveUniform",a,b,c,d,e,f,g)},uc:function(a,b,c,d){a=O.getAttachedShaders(R[a]);
var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=T.indexOf(a[b])},tc:function(a,b){return O.getAttribLocation(R[a],E(b))},rc:function(a,b){te(a,b,4)},qc:function(a,b,c){c?x[c>>2]=O.getBufferParameter(a,b):V(1281)},pc:function(){var a=O.getError()||Dd;Dd=0;return a},oc:function(a,b){te(a,b,2)},nc:function(a,b,c,d){a=O.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},mc:function(a,b){te(a,b,0)},kc:function(a,b,
c,d){a=O.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(x[c>>2]=b)},lc:function(a,b,c){if(c)if(a>=ud)V(1281);else{var d=Ad[a];if(d)if(35716==b)a=O.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.ye;else if(35722==b){if(-1==d.ie){a=R[a];var e=O.getProgramParameter(a,35721);for(b=d.ie=0;b<e;++b)d.ie=Math.max(d.ie,O.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.ie}else if(35381==b){if(-1==d.je)for(a=R[a],e=O.getProgramParameter(a,
35382),b=d.je=0;b<e;++b)d.je=Math.max(d.je,O.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.je}else x[c>>2]=O.getProgramParameter(R[a],b);else V(1282)}else V(1281)},fa:function(a,b,c){if(c){a=O.Ud.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;se(c,d)}else V(1281)},ha:function(a,b,c){if(c){a=O.Ud.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else V(1281)},ea:function(a,b,c){if(c){a=O.Ud.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=
a;se(c,d)}else V(1281)},ga:function(a,b,c){if(c){a=O.Ud.getQueryObjectEXT(U[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else V(1281)},ja:function(a,b,c){c?x[c>>2]=O.Ud.getQueryEXT(a,b):V(1281)},jc:function(a,b,c){c?x[c>>2]=O.getRenderbufferParameter(a,b):V(1281)},gc:function(a,b,c,d){a=O.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(x[c>>2]=b)},fc:function(a,b,c,d){a=O.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},
ec:function(a,b,c,d){if(a=O.getShaderSource(T[a]))b=0<b&&d?D(a,d,b):0,c&&(x[c>>2]=b)},ic:function(a,b,c){c?35716==b?(a=O.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(T[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=O.getShaderParameter(T[a],b):V(1281)},dc:function(a){if(Bd[a])return Bd[a];switch(a){case 7939:var b=O.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ue(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
O.getParameter(a))||V(1280);b=ue(b);break;case 7938:b=ue("OpenGL ES 2.0 ("+O.getParameter(7938)+")");break;case 35724:b=O.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ue(b);break;default:return V(1280),0}return Bd[a]=b},cc:function(a,b,c){c?A[c>>2]=O.getTexParameter(a,b):V(1281)},bc:function(a,b,c){c?x[c>>2]=O.getTexParameter(a,b):V(1281)},_b:function(a,b){b=E(b);var c=0;if("]"==b[b.length-
1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Ad[a]&&Ad[a].Ze[b])&&0<=c&&c<a[0]?a[1]+c:-1},ac:function(a,b,c){ve(a,b,c,2)},$b:function(a,b,c){ve(a,b,c,0)},Wb:function(a,b,c){c?x[c>>2]=O.getVertexAttribOffset(a,b):V(1281)},Zb:function(a,b,c){we(a,b,c,2)},Xb:function(a,b,c){we(a,b,c,5)},Vb:function(a,b){O.hint(a,b)},Ub:function(a){return(a=vd[a])?O.isBuffer(a):0},Tb:function(a){return O.isEnabled(a)},Sb:function(a){return(a=wd[a])?O.isFramebuffer(a):0},
Rb:function(a){return(a=R[a])?O.isProgram(a):0},na:function(a){return(a=U[a])?O.Ud.isQueryEXT(a):0},Qb:function(a){return(a=xd[a])?O.isRenderbuffer(a):0},Pb:function(a){return(a=T[a])?O.isShader(a):0},Ob:function(a){return(a=yd[a])?O.isTexture(a):0},aa:function(a){return(a=zd[a])?O.isVertexArray(a):0},Mb:function(a){O.lineWidth(a)},Lb:function(a){O.linkProgram(R[a]);var b=R[a];a=Ad[a]={Ze:{},ye:0,ie:-1,je:-1};for(var c=a.Ze,d=O.getProgramParameter(b,35718),e=0;e<d;++e){var f=O.getActiveUniform(b,
e),g=f.name;a.ye=Math.max(a.ye,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=O.getUniformLocation(b,g);if(m){var n=Ed(S);c[g]=[f.size,n];S[n]=m;for(var q=1;q<f.size;++q)m=O.getUniformLocation(b,g+"["+q+"]"),n=Ed(S),S[n]=m}}},Kb:function(a,b){3317==a&&(Cd=b);O.pixelStorei(a,b)},Jb:function(a,b){O.polygonOffset(a,b)},ka:function(a,b){O.Ud.queryCounterEXT(U[a],b)},Ib:function(a,b,c,d,e,f,g){(g=xe(f,e,c,d,g))?O.readPixels(a,b,c,d,e,f,g):V(1280)},Hb:function(){},Gb:function(a,b,
c,d){O.renderbufferStorage(a,b,c,d)},Fb:function(a,b){O.sampleCoverage(a,!!b)},Eb:function(a,b,c,d){O.scissor(a,b,c,d)},Db:function(){V(1280)},Bb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?x[d+4*f>>2]:-1;e+=E(x[c+4*f>>2],0>g?void 0:g)}O.shaderSource(T[a],e)},Ab:function(a,b,c){O.stencilFunc(a,b,c)},zb:function(a,b,c,d){O.stencilFuncSeparate(a,b,c,d)},yb:function(a){O.stencilMask(a)},xb:function(a,b){O.stencilMaskSeparate(a,b)},wb:function(a,b,c){O.stencilOp(a,b,c)},vb:function(a,b,c,d){O.stencilOpSeparate(a,
b,c,d)},ub:function(a,b,c,d,e,f,g,m,n){O.texImage2D(a,b,c,d,e,f,g,m,n?xe(m,g,d,e,n):null)},tb:function(a,b,c){O.texParameterf(a,b,c)},sb:function(a,b,c){O.texParameterf(a,b,A[c>>2])},pb:function(a,b,c){O.texParameteri(a,b,c)},ob:function(a,b,c){O.texParameteri(a,b,x[c>>2])},nb:function(a,b,c,d,e,f,g,m,n){var q=null;n&&(q=xe(m,g,e,f,n));O.texSubImage2D(a,b,c,d,e,f,g,m,q)},mb:function(a,b){O.uniform1f(S[a],b)},lb:function(a,b,c){if(288>=b)for(var d=ye[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>
2,c+4*b>>2);O.uniform1fv(S[a],d)},kb:function(a,b){O.uniform1i(S[a],b)},jb:function(a,b,c){if(288>=b)for(var d=ze[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1iv(S[a],d)},ib:function(a,b,c){O.uniform2f(S[a],b,c)},hb:function(a,b,c){if(144>=b)for(var d=ye[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>2,c+8*b>>2);O.uniform2fv(S[a],d)},gb:function(a,b,c){O.uniform2i(S[a],b,c)},eb:function(a,b,c){if(144>=b)for(var d=ze[2*b-1],e=0;e<
2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);O.uniform2iv(S[a],d)},db:function(a,b,c,d){O.uniform3f(S[a],b,c,d)},cb:function(a,b,c){if(96>=b)for(var d=ye[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);O.uniform3fv(S[a],d)},bb:function(a,b,c,d){O.uniform3i(S[a],b,c,d)},ab:function(a,b,c){if(96>=b)for(var d=ze[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>
2];else d=x.subarray(c>>2,c+12*b>>2);O.uniform3iv(S[a],d)},$a:function(a,b,c,d,e){O.uniform4f(S[a],b,c,d,e)},_a:function(a,b,c){if(72>=b){var d=ye[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);O.uniform4fv(S[a],d)},Za:function(a,b,c,d,e){O.uniform4i(S[a],b,c,d,e)},Ya:function(a,b,c){if(72>=b)for(var d=ze[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>
2];else d=x.subarray(c>>2,c+16*b>>2);O.uniform4iv(S[a],d)},Xa:function(a,b,c,d){if(72>=b)for(var e=ye[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);O.uniformMatrix2fv(S[a],!!c,e)},Va:function(a,b,c,d){if(32>=b)for(var e=ye[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],
e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);O.uniformMatrix3fv(S[a],!!c,e)},Ua:function(a,b,c,d){if(18>=b){var e=ye[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(S[a],!!c,
e)},Ta:function(a){O.useProgram(R[a])},Sa:function(a){O.validateProgram(R[a])},Ra:function(a,b){O.vertexAttrib1f(a,b)},Qa:function(a,b){O.vertexAttrib1f(a,A[b>>2])},Pa:function(a,b,c){O.vertexAttrib2f(a,b,c)},Oa:function(a,b){O.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},Na:function(a,b,c,d){O.vertexAttrib3f(a,b,c,d)},Ma:function(a,b){O.vertexAttrib3f(a,A[b>>2],A[b+4>>2],A[b+8>>2])},Ka:function(a,b,c,d,e){O.vertexAttrib4f(a,b,c,d,e)},Ja:function(a,b){O.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>
2])},X:function(a,b){O.vertexAttribDivisor(a,b)},Ia:function(a,b,c,d,e,f){O.vertexAttribPointer(a,b,c,!!d,e,f)},Ha:function(a,b,c,d){O.viewport(a,b,c,d)},k:function(){return 0},qa:function(a,b,c){G.copyWithin(a,b,b+c)},Da:function(a,b,c){return Ae(a,{Be:x[c>>2],se:x[c+4>>2],jf:x[c+8>>2],ff:b,ne:x[c+12>>2],Ie:x[c+16>>2]})},M:function(a,b){a=Y(a);return a?a.requestPointerLock||a.qe?Hd&&Od.be?ne(a):b?(Ld(ne,2,[a]),1):-2:-1:-4},ra:function(){r("OOM")},r:function(){return(Td=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},s:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Be(a,b);return 0},E:function(a,b,c,d){Ce(a,b,c,d,12,"blur");return 0},e:he,i:function(a,b,c){a=Y(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},F:function(a,b,c,d){Ce(a,b,c,d,13,"focus");return 0},v:function(a,b,c,d){if(!Rd())return-1;a=Y(a);if(!a)return-4;De(a,b,c,d,"fullscreenchange");De(a,b,c,d,"webkitfullscreenchange");
return 0},p:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Ee(a,b,c,26,"gamepadconnected");return 0},o:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Ee(a,b,c,27,"gamepaddisconnected");return 0},y:function(a,b,c,d){Fe(a,b,c,d,2,"keydown");return 0},w:function(a,b,c,d){Fe(a,b,c,d,1,"keypress");return 0},x:function(a,b,c,d){Fe(a,b,c,d,3,"keyup");return 0},rb:function(a,b,c,d){Ic(function(){I.get(a)(b)},c,d,b)},K:function(a,b,c,d){He(a,
b,c,d,5,"mousedown");return 0},I:function(a,b,c,d){He(a,b,c,d,33,"mouseenter");return 0},H:function(a,b,c,d){He(a,b,c,d,34,"mouseleave");return 0},L:function(a,b,c,d){He(a,b,c,d,8,"mousemove");return 0},J:function(a,b,c,d){He(a,b,c,d,6,"mouseup");return 0},z:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Od||document.body.he||document.body.qe))return-1;a=Y(a);if(!a)return-4;Ie(a,b,c,d,"pointerlockchange");Ie(a,b,c,d,"mozpointerlockchange");Ie(a,b,
c,d,"webkitpointerlockchange");Ie(a,b,c,d,"mspointerlockchange");return 0},u:function(a,b,c,d){Je(a,b,c,d);return 0},A:function(a,b,c,d){Ke(a,b,c,d,25,"touchcancel");return 0},C:function(a,b,c,d){Ke(a,b,c,d,23,"touchend");return 0},B:function(a,b,c,d){Ke(a,b,c,d,24,"touchmove");return 0},D:function(a,b,c,d){Ke(a,b,c,d,22,"touchstart");return 0},t:function(a,b,c){if(!fe[1])return-4;Le(a,b,c);return 0},G:function(a,b,c,d){a=Y(a);return"undefined"!==typeof a.onwheel?(Me(a,b,c,d),0):-1},j:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},sa:function(a,b){try{var c=0;Oe().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);w[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof vc&&d instanceof J||r(d),d.Xd}},ua:function(a,b){try{var c=Oe();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0}catch(e){return"undefined"!==typeof vc&&e instanceof J||r(e),e.Xd}},m:function(a){try{var b=yc(a);fc(b);return 0}catch(c){return"undefined"!==typeof vc&&
c instanceof J||r(c),c.Xd}},va:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=x[b+(8*f+4)>>2],m=e,n=x[b+8*f>>2],q=g,p=void 0,t=w;if(0>q||0>p)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(16384===(m.node.mode&61440))throw new J(31);if(!m.Ld.read)throw new J(28);var u="undefined"!==typeof p;if(!u)p=m.position;else if(!m.seekable)throw new J(70);var v=m.Ld.read(m,t,n,q,p);u||(m.position+=v);var z=v;if(0>z){var B=-1;break a}a+=z;if(z<g)break}B=
a}x[d>>2]=B;return 0}catch(F){return"undefined"!==typeof vc&&F instanceof J||r(F),F.Xd}},Ga:function(a,b,c,d,e){try{var f=yc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;hc(f,a,d);za=[f.position>>>0,(y=f.position,1<=+Math.abs(y)?0<y?(Math.min(+Math.floor(y/4294967296),4294967295)|0)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];x[e>>2]=za[0];x[e+4>>2]=za[1];f.we&&0===a&&0===d&&(f.we=null);return 0}catch(g){return"undefined"!==typeof vc&&g instanceof J||r(g),
g.Xd}},l:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var g=ic(e,w,x[b+8*f>>2],x[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}x[d>>2]=m;return 0}catch(n){return"undefined"!==typeof vc&&n instanceof J||r(n),n.Xd}},td:function(){return window.innerHeight},ud:function(){return window.innerWidth},g:function(a){var b=Date.now();x[a>>2]=b/1E3|0;x[a+4>>2]=b%1E3*1E3|0;return 0},a:Aa,ya:function(a,b){if(0===a)return nb(),-1;var c=x[a>>2];a=x[a+4>>2];if(0>a||999999999<a||0>c)return nb(),
-1;0!==b&&(x[b>>2]=0,x[b+4>>2]=0);b=1E6*c+a/1E3;for(c=zc();zc()-c<b/1E3;);},N:function(){},c:function(){return 0},Ea:function(){return 0}};
(function(){function a(e){h.asm=e.exports;I=h.asm.vd;bb("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return hb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:Ve};ab("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return wa||"function"!==typeof WebAssembly.instantiateStreaming||
eb()||cb("file://")||"function"!==typeof fetch?c(b):fetch(db,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Te=h.___wasm_call_ctors=function(){return(Te=h.___wasm_call_ctors=h.asm.wd).apply(null,arguments)};h._main=function(){return(h._main=h.asm.xd).apply(null,arguments)};
h.___em_js__getBrowserWidth=function(){return(h.___em_js__getBrowserWidth=h.asm.yd).apply(null,arguments)};h.___em_js__getBrowserHeight=function(){return(h.___em_js__getBrowserHeight=h.asm.zd).apply(null,arguments)};var H=h._malloc=function(){return(H=h._malloc=h.asm.Ad).apply(null,arguments)};h._CCanvas_dropEventForSDL=function(){return(h._CCanvas_dropEventForSDL=h.asm.Bd).apply(null,arguments)};
var ob=h.___errno_location=function(){return(ob=h.___errno_location=h.asm.Cd).apply(null,arguments)},Ue=h._emscripten_GetProcAddress=function(){return(Ue=h._emscripten_GetProcAddress=h.asm.Dd).apply(null,arguments)},Fa=h.stackSave=function(){return(Fa=h.stackSave=h.asm.Ed).apply(null,arguments)},Ga=h.stackRestore=function(){return(Ga=h.stackRestore=h.asm.Fd).apply(null,arguments)},Ea=h.stackAlloc=function(){return(Ea=h.stackAlloc=h.asm.Gd).apply(null,arguments)};
h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.Hd).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.Id).apply(null,arguments)};h.ccall=Da;h.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(f){return"number"===f});return"string"!==b&&e&&!d?Ca(a):function(){return Da(a,b,c,arguments,d)}};h.addRunDependency=ab;h.removeRunDependency=bb;h.FS_createPath=mc;h.FS_createDataFile=oc;h.FS_createPreloadedFile=sc;h.FS_createLazyFile=rc;h.FS_createDevice=N;h.FS_unlink=bc;var We;
function ra(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}$a=function Xe(){We||Ye();We||($a=Xe)};
function Ye(a){function b(){if(!We&&(We=!0,h.calledRun=!0,!Ba)){h.noFSInit||kc||(kc=!0,jc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?N("/dev","stdin",h.stdin):ac("/dev/tty","/dev/stdin"),h.stdout?N("/dev","stdout",null,h.stdout):ac("/dev/tty","/dev/stdout"),h.stderr?N("/dev","stderr",null,h.stderr):ac("/dev/tty1","/dev/stderr"),dc("/dev/stdin",0),dc("/dev/stdout",1),dc("/dev/stderr",1));mb(Ta);Kb=!1;mb(Ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(Ze){var c=a,d=h._main;
c=c||[];var e=c.length+1,f=Ea(4*(e+1));x[f>>2]=Ma(da);for(var g=1;g<e;g++)x[(f>>2)+g]=Ma(c[g-1]);x[(f>>2)+e]=0;try{var m=d(e,f);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(h.onExit)h.onExit(m);Ba=!0}ea(m,new ra(m))}}catch(n){n instanceof ra||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Wa.unshift(c);mb(Wa)}}
a=a||ca;if(!(0<Ya)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Xa();mb(Sa);0<Ya||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=Ye;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Ze=!0;h.noInitialRun&&(Ze=!1);noExitRuntime=!0;Ye();
